.MODEL SMALL
.data 
cad db ?
.code 

;	28/03/2016

INICIO:
	MOV AX,@DATA
	MOV DS,AX
	MOV SI,0;


PIDE:
	MOV AH,7h
			;LE ASIGNO  EL NUMERO 7 AL REGSITRO AH PARA LA INT
			;ENTRADA POR TECLADO CON ECO DESACTIVADO 
	INT 21H
	MOV CAD[SI],AL 	;ALMACENA EL CARACTER EN CAD[SI]
	INC SI			;INCREMENENTA EL APUNTADOR
	CMP AL,13D		;ES ENTER?
	JNE PIDE 		;

	DEC SI			;QUITAMOS EL ENTER


	MOV CAD[SI],'$'	;REEPLAZAMOS POR '$' PARA INDICAR FINAL DE CADENA
	LEA DX,cad 		;OBTIENE LA DIRECCION EFECTICA DE LA VARIABLE
	MOV AH,9H
	INT 21H
LOOP1:
	MOV AH,1		;DECALRO LA ETIQUETA EN LOOP1
					;LE ASIGNO EL NUMERO 7 AL REGISTRO 
 AH PAR
	INT 21H 		;MANDO A LLAMAR LA INT 21H
	MOV CAD[SI],AL 	;EL CARACTER TECLADO SE GUARDO EN AL Y SE ALMACENA EN CAD[SI]
	CMP AL,13D		; SI = SI +1
	JNZ LOOP1		; SE COMPARA SI ES ENTER
	DEC SI			
LOOP2:
	DEC SI			; DECREMENTO A SI
	MOV DL,CAD[SI]	; DL EL CONTENIDO DE CAD[SI]
	MOV AH,2		; USO DE LA OPCION 2 PARA EXHIBIR LA SALIDA
	INT 21H			; CMP SI,0
	JNZ LOOP2	

FIN: 
	MOV AH,4CH
	INT 21H

.STACK
END INICIO